// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx6iM0QB17Xjf5zhPMa45jIKEwMSzO4N4',
    appId: '1:631663251271:web:822a968a8c7faeab970662',
    messagingSenderId: '631663251271',
    projectId: 'managemen-sekolah-f352d',
    authDomain: 'managemen-sekolah-f352d.firebaseapp.com',
    storageBucket: 'managemen-sekolah-f352d.firebasestorage.app',
    measurementId: 'G-VQWNGMHQSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlONxMfvI_n0al8_gHrPrj2S2MMQHpBSc',
    appId: '1:631663251271:android:6407fc58ae059d32970662',
    messagingSenderId: '631663251271',
    projectId: 'managemen-sekolah-f352d',
    storageBucket: 'managemen-sekolah-f352d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjGwA9VgbM0fY9tmplQ2HbViD469OHxkQ',
    appId: '1:631663251271:ios:352ead690a9b97a6970662',
    messagingSenderId: '631663251271',
    projectId: 'managemen-sekolah-f352d',
    storageBucket: 'managemen-sekolah-f352d.firebasestorage.app',
    iosBundleId: 'com.example.manajemensekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjGwA9VgbM0fY9tmplQ2HbViD469OHxkQ',
    appId: '1:631663251271:ios:352ead690a9b97a6970662',
    messagingSenderId: '631663251271',
    projectId: 'managemen-sekolah-f352d',
    storageBucket: 'managemen-sekolah-f352d.firebasestorage.app',
    iosBundleId: 'com.example.manajemensekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx6iM0QB17Xjf5zhPMa45jIKEwMSzO4N4',
    appId: '1:631663251271:web:a8245a1a7fce7803970662',
    messagingSenderId: '631663251271',
    projectId: 'managemen-sekolah-f352d',
    authDomain: 'managemen-sekolah-f352d.firebaseapp.com',
    storageBucket: 'managemen-sekolah-f352d.firebasestorage.app',
    measurementId: 'G-V702NT1KKY',
  );
}
